services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  reservation_service:
    build:
      context: ./ReservationService
      dockerfile: Dockerfile
    container_name: ReservationService
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8070:8070"

volumes:
  db-data: